"""Added Tables

Revision ID: 1c4a27716c47
Revises: a50a34f9bf63
Create Date: 2023-11-04 21:35:31.676468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4a27716c47'
down_revision = 'a50a34f9bf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
