"""Added data to tables

Revision ID: 887524be99fc
Revises: 1c4a27716c47
Create Date: 2023-11-04 23:16:52.688014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887524be99fc'
down_revision = '1c4a27716c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
